django_microservice_auth/__init__.py,sha256=47DEQpj8HBSa-_TImW-5JCeuQeRkm5NMpJWZG3hSuFU,0
django_microservice_auth/auth.py,sha256=hHNnndcaPwF-BsYGloTVwF0RIKfiIq3UOiYKg4xii0I,2757
django_microservice_auth/exceptions.py,sha256=Jz3UE7YB9WvWu2cnNhrHCCn8LaQ1qhpZ2YKEbTstIdY,52
django_microservice_auth-0.0.2.dist-info/METADATA,sha256=7Ox9_-mCjgQgveJ2kSINGI7ka_US32bV2gPyL_Q1g3Q,371
django_microservice_auth-0.0.2.dist-info/WHEEL,sha256=Z-nyYpwrcSqxfdux5Mbn_DQ525iP7J2DG3JgGvOYyTQ,110
django_microservice_auth-0.0.2.dist-info/top_level.txt,sha256=neeCnDo69u4OLdNfiREakJ7CSd0as5uB1DbJKKewy08,25
django_microservice_auth-0.0.2.dist-info/RECORD,,
